
/**
 * Action enum.
 * @author koray
 *
 */
public enum Action {
	// Smelter actions
	SMELTER_CREATED,
	SMELTER_STARTED,
	SMELTER_FINISHED,
	SMELTER_STOPPED,
	
	// Constructor actions
	CONSTRUCTOR_CREATED,
	CONSTRUCTOR_STARTED,
	CONSTRUCTOR_FINISHED,
	CONSTRUCTOR_STOPPED,
	
	// Transporter actions
	TRANSPORTER_CREATED,
	TRANSPORTER_TRAVEL,
	TRANSPORTER_TAKE_INGOT,
	TRANSPORTER_DROP_INGOT,
	TRANSPORTER_STOPPED
}
